#!/usr/bin/env python

#mini launcher script: codename-o (Python port)
version='2.1'
# made by syfluqs <syfluqs@gmail.com>


#importing stuff we need.
import sys,os,subprocess
from terminal import *

#figuring out the arguement(s)
args = sys.argv[1:]

############################################################################
#declaring variables

home=os.environ['HOME']
docs=home+'/Documents/'
pics=home+'/Pictures/'
git=docs+'git/'
down=home+'/Downloads/'
todofile=home+'/.o/todo'
browser='google-chrome'
editor='gvim '
musicplayer='deadbeef --play-pause'
filebrowser='pcmanfm'
curlocation=os.path.abspath(__file__)
redir=' 2> /dev/null'
out=''
cmd=''

############################################################################
# Define all functions here

def doc():
    print 'o launcher v'+version+' \nThe Python port \n\nmade by: syfluqs <syfluqs@gmail.com>'

def msg(a):
    print green(a)

def err(a):
    print red('ERROR: '+a)

def exe(s):
    #os.system(s+' &')
    try:
        global cmd
        global stdout
        cmd = subprocess.Popen(s, shell=True, stdout=subprocess.PIPE) 
        global out
        out = cmd.stdout.read()
    except OSError:
        err('No Such file or directory')

def blobby():
    os.system('blobby'+redir)
    msg('Starting Blobby volley...')

def install():
    if len(args)<2: err('Package name required.')
    else:
        ec=os.system('sudo apt-get install '+args[1])
        if ec==0: msg('Successfully installed '+args[1])

def edit():
    if len(args)<2:
        os.system(editor+curlocation+redir)
    else:
        os.system(editor+args[1]+redir)

def internet():
    #defining a dict of bookmarks
    bookmarks = {
    'git':'https://github.com',
    'i':'--incognito',
    'cc':'http://www.codecademy.com'
    }
    #checking sub-arguement.
    if len(args)<2:
        exe(browser)
    else:
        subarg=' '.join(args[1:])
        if subarg in bookmarks:
            exe(browser+" "+bookmarks[subarg])
        else:
            exe(browser+" \'https://www.google.co.in/search?q="+subarg+'\'')

def checkX():
    if os.path.isfile('/tmp/.X0-lock'):
        msg('X is running, falling back...')
    else:
        msg('X is not running. Starting it...')
        exe('startx')

def files():
    bookmarks = {
    'down':down,
    'docs':docs,
    'pics':pics,
    'git':git
    }
    #checking subarg
    if len(args)<2:
        exe(filebrowser)
    else:
        subarg=args[1]
        if subarg in bookmarks:
            exe(filebrowser+" "+bookmarks[subarg])
        else:
            exe(filebrowser+" "+subarg)

def bluetooth():
    exe('bluetooth-applet'+redir)
    exe('bluetooth-sendto'+redir)

def music():
    exe(musicplayer)

def getnetusage():
    exe('sudo ifconfig eth0')
    print out
    for line in cmd.stdout:
        if "RX" in line:
            print line
        

############################################################################
# the cmdlist
# is is an index of the arguements to their respective functions
# o checks if the arg is in cmdlist and runs the respective function
# if not present, o will pass it on to os.system

cmdlist = {
   'blby':'blobby()',
   'i':'install()',
   'e':'edit()',
   'gc':'internet()',
   's':'checkX()',
   'f':'files()',
   'bsend':'bluetooth()',
   'm':'music()',
   'neus':'getnetusage()'
    }

############################################################################

#running the provided arguement if any. If no argements, display doc

#if len(args)!=0: 
#    i=0
#    while i < len(args):
#        os.system(args[i]+' &')
#        i+=1
#
#else: 
#    doc()

#processing and running
if len(args)!=0:
    cmd = args[0]
    print cmd
#    func=globals()[cmdlist.get(cmd,exe(cmd))]()
#    getattr(__main__,cmdlist.get(cmd,'exe(cmd+\' &\')'))
    exec cmdlist.get(cmd,'exe(\''+cmd+'\')')
else:
    doc()
